### ISSUE TITLE
添加中國「平安银行IC借记卡普卡」

### ISSUE THREAD

**Issue by BugHeroZhang** [HarukaKinen/Cardentify#5]
![cardBackgroundCombined@2x](https://github.com/user-attachments/assets/2c22d9af-0c4c-4ec6-8c28-7d6c199b1d66)

卡片分類：Standard Debit - Union Pay

**Comment by Kotoki1337** [comment]
有 Bin 头吗

**Comment by BugHeroZhang** [comment]
> 有 Bin 头吗

是的，623058[https://bincheck.io/zh/details/623058](url)

**Comment by Kotoki1337** [comment]
Done
